const verbs1Sentences = {
    "They hope I come": ["Mereka berharap saya datang"],
    "I think at the garden": ["Saya berpikir di kebun"],
    "You successfully changed": ["Kamu berhasil berubah", "Anda berhasil berubah"],
    "They do not move": ["Mereka tidak bergerak"],
    "We play together": ["Kami bermain bersama"],
    "Who is that with you": ["Siapa itu bersamamu", "Siapa itu bersama kamu"],
    "He stands up and walks": ["Dia berdiri dan berjalan"],
    "This is not progressing": ["Ini tidak berkembang"],
    "I got with him": ["Saya pergi bersama dia", "Aku pergi bersama dia"],
    "They meet me": ["Mereka bertemu saya", "Mereka bertemu Aku"],
    "She learns to read at school": ["Dia belajar membaca di sekolah"],
    "Andi plays with me at school": ["Andi bermain dengan saya di sekolah", "Andi bermain bersama saya di sekolah"],
    "I walk, they stop": ["Saya berjalan mereka berhenti", "Aku berjalan mereka berhenti"],
    "Tini is at (formal) home with Dimas": ["Tini berada di rumah dengan Dimas", "Tini di rumah dengan Dimas", "Tini di rumah bersama Dimas", "Tini berada di rumah bersama Dimas"],
    "You stand up and walk there because I walk and sit here": ["Kamu berdiri dan berjalan di sana karena saya berjalan dan duduk di sini", "Kamu berdiri dan berjalan di situ karena saya berjalan dan duduk di sini", "Kamu berdiri dan berjalan di sana karena Aku berjalan dan duduk di sini", "Kamu berdiri dan berjalan di situ karena Aku berjalan dan duduk di sini"],
    "They hope to meet me": ["Mereka berharap bertemu saya", "Mereka berharap bertemu Aku"],
    "I know they're coming home": ["Saya tahu mereka pulang", "Aku tahu mereka pulang"],
    "They gather at the school": ["Mereka berkumpul di sekolah"],
    "I go to the office to work": ["Saya pergi ke kantor untuk bekerja"],
    "I come from there but live here": ["Saya berasal dari di sana tapi tinggal di sini", "Saya berasal dari di situ tapi tinggal di sini", "Aku berasal dari di sana tapi tinggal di sini", "Aku berasal di sana namun tinggal di sini", "Aku berasal di situ namun tinggal di sini", "Saya berasal dari di situ namun tinggal di sini", "Saya berasal dari di sana namun tinggal di sini"],
    "That cake is moving": ["Kue itu bergerak"],
    "That price is valid here": ["Harga itu berlaku di sini"],
    "They play and learn at the market": ["Mereka bermain dan belejar di pasar"],
    "We swim together": ["Kami berenang bersama"],
    "You depart from home to work": "Kamu berangkat dari rumah ke kantor",
};
