const verbs3Sentences = {
    "I enter that building over there": ["Saya masuk gedung itu di sana"],
    "I want to eat fried rice with you": ["Saya ingin makan nasi goreng dengan kamu"],
    "They forget me": ["Mereka lupa saya"],
    "I remember this cat": ["Saya ingat kucing ini"],
    "The ball falls": ["Bola jatuh"],
    "He returns": ["Dia kembali"],
    "I do not agree with that dog": ["Saya tidak setuju dengan anjing itu"],
    "I buy apples and you like oranges": ["Saya membeli apel dan kamu suka jeruk", "Saya membeli apel, kamu suka jeruk"],
    "I know, I forget": ["Saya tahu, saya lupa"],
    "He appears from the kitchen": ["Dia muncul dari dapur"],
    "The wallet is in the kitchen": ["Dompet ada di dapur"],
    "I do not understand you": ["Saya tidak mengerti kamu"],
    "They bring a black umbrella": ["Mereka membawa payung hitam"],
    "I finished reading": ["Saya selesai membaca"],
    "Sorry, you're wrong": ["Maaf kamu salah"],
    "He writes menus": ["Dia menulis menu", "Dia menulis menu menu", "Dia menulis menu-menu"],
    "I like your letter": ["Saya suka suratmu", "Saya suka surat kamu"],
    "I cannot enter": ["Saya tidak bisa masuk"],
    "I can wear this belt": ["Saya bisa memakai sabuk ini"],
};
